# Generated by Django 2.1.3 on 2019-01-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='created_at',
            new_name='data',
        ),
    ]
