# Generated by Django 2.1.3 on 2019-01-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20190106_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='data',
            new_name='created_at',
        ),
    ]
